### PR TITLE
demo demo

### PR DESCRIPTION
**Pull request by mcdurdin**
This is a new feature in the readme.
 
# User Testing

* TEST_SPLELING: make sure all the spleling is okay.
* TEST_GRAMMAR: is the grammar goodness too?

### CODE REVIEW

**Comment by mcdurdin** [comment]
* TEST_SPLELING: FAILED you can't even spell 'demo'

**Comment by mcdurdin** [comment]
TEST_SPLELING: PASSED I don't care that it's spelled wrong
TEST_GRAMMAR: PASSED Also good mate

**Comment by mcdurdin** [comment]
@keymanapp-test-bot retest

**Comment by ermshiperete** [comment]
@keymanapp-test-bot retest TEST_SPLELING, TEST_GRAMMAR

**Pull request closed without merging**
